api_auth_sign_in:
  path: /api/auth/sign-in
  methods: [POST]
sign-up:
  path: /sign-up/{hash}
  controller: App\Controller\AuthController::signUp
sign-in:
  path: /sign-in
  controller: App\Controller\AuthController::signIn

home:
  path: /users
  controller: App\Controller\HomeController::home
api-all-users:
  path: /api/users
  controller: App\Controller\HomeController::allUsers

profile:
  path: /profile
  controller: App\Controller\UserController::profile
api-profile:
  path: /api/profile/{id?}
  controller: App\Controller\UserController::profileData
user-id:
  path: /api/user-id
  controller: App\Controller\UserController::userId

invite:
  path: /invite
  controller: App\Controller\InviteController::invite
api-invite-create:
  path: /api/invite-create
  controller: App\Controller\InviteController::createInvite

talk-ids:
  path: /api/talk-ids
  controller: App\Controller\TalkController::talkIdentifiers
talk:
  path: /talk
  controller: App\Controller\TalkController::talk
api-talk:
  path: /api/talk/{id}
  controller: App\Controller\TalkController::apiTalk
